/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_a16lao_wyh_jni_JNIKit */

#ifndef _Included_com_a16lao_wyh_jni_JNIKit
#define _Included_com_a16lao_wyh_jni_JNIKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_a16lao_wyh_jni_JNIKit
 * Method:    pow
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_a16lao_wyh_jni_JNIKit_pow
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_a16lao_wyh_jni_JNIKit
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_a16lao_wyh_jni_JNIKit_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
